"""add_created_at_to_usuarios

Revision ID: b033fbef18b6
Revises: 6ad73fa90c98
Create Date: 2026-08-26 16:00:52.496705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b033fbef18b6'
down_revision: Union[str, Sequence[str], None] = '6ad73fa90c98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notificacoes', sa.Column('lida', sa.Boolean(), nullable=True))
    op.add_column('notificacoes', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('usuarios', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'created_at')
    op.drop_column('notificacoes', 'created_at')
    op.drop_column('notificacoes', 'lida')
    # ### end Alembic commands ###
